---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-data
  namespace: home
  labels:
    app: actual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
