---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: focalboard
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: focalboard
      version: 0.5.0
      sourceRef:
        kind: HelmRepository
        name: mattermost
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: mattermost/focalboard
      tag: 0.9.0

    env:
      TZ: '${TIMEZONE}'

    ingress:
      enabled: true
      ingressClassName: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        - host: 'focal.${SECRET_DOMAIN}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - 'focal.${SECRET_DOMAIN}'
          secretName: 'focalboard-tls'

    persistence:
      enabled: true
