---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: '^(kind)$'
    age: >-
      age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: >-
      age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
