---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      chart: gitea
      version: 5.0.6
      sourceRef:
        kind: HelmRepository
        name: gitea-charts
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        - 'git.${SECRET_DOMAIN}'
      tls:
        - hosts:
            - 'git.${SECRET_DOMAIN}'
          secretName: 'gitea-tls'
