# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: gitea-admin-secret
    namespace: dev
stringData:
    username: ENC[AES256_GCM,data:BfeaVLLqww==,iv:Nn124lQVRSagWQAMKHb8go0HijuKhLzPm4H7kdTIS0A=,tag:0F7F31ngmwd0Helo3s94kw==,type:str]
    password: ENC[AES256_GCM,data:aR4N1OZPppgylh3SAGJ6iQLn/UYMahg=,iv:qC5yC/5iLtqnZcumKlNRt9Q5xlckEY+mCS6NaIbI+i0=,tag:xebC8pfhijTn/l38e2kMqQ==,type:str]
    email: ENC[AES256_GCM,data:f8+MXCG5Z5jJzifzbkrAuKyK1Nn3BDq4Nw==,iv:DkKjShS8FMBWkx6LbiIqDjyPl/hN1QG78cjSYqqOQuo=,tag:jHs/huqsffSWb3B0p6vN0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIclRjMWljZ1ZiZnUydW5X
            V3cvY3FxQkhjMWdleEprZDhsSVpLYXQrOHg0CmYvVEEvL3JJYTQ0bGNqT3ZqOUtU
            VHZwUDg3WDZqRlp2aWFkMFBYbWFoVGMKLS0tIFJzSUxxalUrRlVhS1pWMHdzbHRn
            enkzbmEwdnlhdjVVL2t3Wll2Slh0YjgKq3tbwV4IZywOt9R9h0NDd253KKQ1rdA1
            x4PORoN+d5HJvKhLaarIyR1uwpWkq/u0gyOcc2ptd17dw12tuSKgGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-04-30T13:06:19Z"
    mac: ENC[AES256_GCM,data:pl4eIb950yU9qYQ28uceLfddYtUstde6QVoEGR8wv8qrDePJZ85lPPF0UQfMQieSoymcmUB/ERmVsBjzMpuN8XQJkNocL3iAtDguZ/FjHbHivkAhn8t+S1LoSIdXPkzjuvnYRvwalBALktbMzCBmADN4B52qv8Datq5CR5NHYAA=,iv:YU4QUIrQgDVqEk02+befI7fhBd46wU+XzqaAHQyq9VU=,tag:kWdLCw54ZYVuF6AKKRs8QQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
