# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: mosquitto-config
    namespace: home
stringData:
    mqtt.conf: ENC[AES256_GCM,data:KdS80l49KdkR18osF+NmONIbvwlj82JHgYDpBKzwHZcxgIJxvgO0y9V+Iu4d1MN5FOeY8Fmut7Zz22TY5piPmOff7p5v/OfduY5THvLh7k/sYc/VsETMRHsTM3YKXMQ=,iv:3Z3KfzNoqE/m91M7KMqnEXufsje340etPPLItxtMN+g=,tag:5E8LJnbKLBme/trrIo03Iw==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:+QQNLv+afQLzZJVgRqLvAwrsbjrl/GRwdOiypWqfFPv8dOGx6q/igu1wwBp/3q1EEunqf1lKrAWJpYxryAXMoZEkC3Fhw7XZ+PJ2O2YGUlnCo1KQj4GyReaQCuKAAoHfwk5+0P09/YWAJ3PJkslHRDsdIrV9lUcg,iv:pKSML3JGZ4zsP88NzFbZNjwrU9MPa/fFZVrIyrk/DUY=,tag:ZIPCvBHEGKVFiyl6CV9FDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-09-19T23:02:44Z'
    mac: ENC[AES256_GCM,data:8ollfiYQ6gHtoMnKWt3jOsmh5nUobcNIS3opQ4IdBy0noTlQ1Vpm+6sxxggtHQJd/5v9E4pdzcg9ejqE6xwFnX/Znun7dYznXOpgLedY1mQhXUC89vPVRXl6APicS1iZj73ub6VDqvu2ivQ5sRliu/WDWQqaHfl2dXlRjIxfenQ=,iv:ob/38WUEasQfipdXxRSK4ztLZu6ZlP6wqrw3Upl6pag=,tag:FtL0KZgaLZY+/FG/0H34LQ==,type:str]
    pgp:
    -   created_at: '2021-09-19T23:02:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9JytBw6RLnDARAAvs535IJ/twLnwoK8e11bz6a+7u46l7ywG0dk1FGWjZw2
            N/5BgqLBAUUWOTqyyuQhwc8m+/DzpoahbgYu8EKf/lBfu3v+fdKo+Vr4jDP2UAwv
            PalU8F0a3EfIKwNi0psU2VcuwlFpgiFVq6RBZ5w7A/ZtEeQN1Y55Eym11Z+nc3eJ
            Tij04SSO8lN2+fw+ZE1A3tsRoPrMNPOl8zx4Ou1UPhfRblLAtBOkc3gemjBEr+qm
            OFa4XEQOo44l6XSNHD6pF0c79afyWsQeh7A8wONZSd4ru9/gC7RQt9EfvIC3BIet
            KSuIIKnXDlJI6WD/6mxbaYIxE7fTV9AjNl2vAdOWvXXvYeBX4b7SvCTCV+PvGzBT
            AWiAIiaXmm/YIMNII214FozCndZg9KrCjq96eFz5w0ZJP7Zj/54yyh68tp+yu5HX
            aa7YeNobonXZVGZn/uxtHziB2Wo9AUyOEl7QQDobQxwonBNQTSNpZbeXYtErWz/2
            RRnz+QcrlrdTQiDKTx7mPj0gVEfByYg+lr+WCKNmHwYtERRWuDgRqVf27GLKgG8d
            n4y4yPGKcgUuXJWBLzcCa2r2M9H2nYuPYlDWtXxxpn6SpOmGTnFA9EKfmq+WTJ+T
            ZwhsbiGjEBdc7+Fi4NvT5FwVNjwyjkF4C1iFh4qaP9tLRk1GHndjMRECsyRU0LjS
            XgGM7NsAzCCuuSAEYhne9wFS0+fBRm0v2HMst/Ec721djlQoJLbvLdUcGhngXEXJ
            PIxhs/uMawhTsXCSsswIW48I8/b+P4IimC3vvdLDRAjbYG7xwWMbgkLRQOTuN3I=
            =smp2
            -----END PGP MESSAGE-----
        fp: BE13BE8779CC7A53B2617A7EB59E605BE03ACB5F
    -   created_at: '2021-09-19T23:02:43Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyHd4YJTb9uqAQ//bt9aow4LvzFeeu9nB7BzIQMktjavUQM8Z2Hr7xe5dTRK
            TTe/ll4cF/mzQwszpA0CktFgyoSxE48GTKDU5Cz5hOsvGWk1VDXdQZpQTX/cKomJ
            Bkwhy+lgduC9EWGq2vw2WH8vV4qQv8qEyKQCu7+BVn32V1WCc9GaljgHvdR6ieZl
            35Mv/2QQ1RBWQGemJsuSQSSFTl+K6CkDcOOl6h9VkEdRjslyxGF2FvR5DpXDGrxY
            xqwDRdCtyvzMKyNhpaATWDpzOZ2CH6cdH+2lOFwvXWSctdjYeoER9YxdEc23m429
            MzRQbQgr2u5I0m/r1ijNThg6UQjaRPky/e6xjwYoDABhF7uRQRy5Gs541RbRuyil
            pUa7YYW5dS4yaLvx4BXm1NfmSNZXOpuqKrXBh2o8QWffiXZ6C5teqcoSzqfEA84l
            xLFJ3tlzo7D+t/ital1R2geLRO1uJ05jdwduKsMrj9x8bw/YsMyKaFlFrQQHid1e
            ognvDTpx2VnDO62XhvqRu9ffa/jVtqUwsCJk4J+QuEdcgBKnVlYaTwxqcbmQ+UQI
            HdhbGjOFXg5niyPvmD40JtCsOokUQ+64jTV7nhJEXf9CT2qEJ6KRevaIODRwRQbi
            yPOSxvFevbty14Anwwb0MuIbyN5liXIo/EOPkFB3AoqHKqpwweg4pzuZQ+jv0hLS
            UQHtWsgMyEavdcAat9CfsURqM8gSytEc8XPcta0cBV17ZQnoc1qB0HUSU7Y9BEM3
            knP1gnwFmXpzeComBW1cdW13mRPokECh4lG87KD5GxKfKg==
            =6o6x
            -----END PGP MESSAGE-----
        fp: 0F516E8261E8D4D03F62114EBD387FF7BC10AA9D
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
