# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:AFfb6A0BuqXuGhs6M0UGjPe+GuNfoQoxNw==,iv:Dw5hKG6uiv4bNK0823p+F2XThGzMBlLK4xlq7Uhz0jQ=,tag:82UAxRT4Bp4BGMTH0v8i0g==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Mb8rbSXMkW5VYWiu5poFmhXou2S106PmV5iv11jAcOwIEE/E+zfurw==,iv:XFMWmRdmRecHQDmKWua9wssO+Iasp/nQbe08XxS0NSE=,tag:b5xl0U0n1sU1sLjyuZ5ezA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:TP7gk29OE9UwZu4+vQ==,iv:nTM5u0cucH0NnfBVa0REszYYQx59LH2H44JzlwZYf3w=,tag:1/rJcOSm7kKBtpWhuPQRVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHenJUWjVXSXdUd2RMbEdI
            eFhLUTBNMjlUYkgrRDQ1ZkhjS082QS9TN1VFCjBwdGh5ZEZ3YUxMV01KRVRkS29E
            NEhVN0I0ZW1HKzZBTzkzYTNlNzdFUFkKLS0tIHJxTmp1ZnM5UDRRZXZBTDZsOVZw
            NU9FOXlMTnd6MzFDenB4bEFRQlk5eGsKPj1ybqzML7URGBfZExWvhoCxujKPmN0N
            6raQSYfscCjy8f5kr7NP6e6R/u3WChliIYGprvea4/p3r0E47SK2DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T02:35:27Z"
    mac: ENC[AES256_GCM,data:JHAaLGzNOZbiWgaVeao9XSeI9/sCfoZp5EnfirhqguHy3GtDAZT934xozbG/sxtWw2Vrjo7y3+XuEcAc5a/HLJUaf+tvgVzeF6iqMpHAMlq6hMQ7yEou7w1A70pFx2bm0CqVd14X3wt4zUw6yLi4EKs7o8W+y/9SZVZYi1XiCcA=,iv:GO0mHv/R+UTfU8hidqdiK7dqo3PTzG1UfPnYQ5ua2fQ=,tag:BZ6v+0DmH9ilps2YiFnSpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
