---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.204
    worker:
      hosts:
        k8s-1:
          ansible_host: 192.168.1.162
          rook_devices:
            - /dev/nvme0n1
