---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deluge-config-v1
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # FIXME
  storageClassName: local-path
