---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: deluge
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: deluge
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/deluge
      tag: version-2.0.3-2201906121747ubuntu18.04.1

    env:
      TZ: 'America/Chicago'

    hostname: deluge

    # podAnnotations:
    #   setGateway: 'true'

    # service:
    #   main:
    #     ports:
    #       http:
    #         port: 8080
    #   bittorrent:
    #     enabled: true
    #     type: LoadBalancer
    #     externalIPs:
    #       - "192.168.1.152"
    #     ports:
    #       bittorrent:
    #         enabled: true
    #         port: 51413
    #         protocol: TCP
    #         targetPort: 51413
    #     externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'deluge.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'deluge.${SECRET_DOMAIN}'

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: deluge-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs
        mountPath: /media

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
