# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:ykp+Cv0ffL09lAE/yet94Tx4Uinme3d6l/aVnIRIQKlAMASXEQ==,iv:+LyzPaazva8lzlLAdNFsxJVrf+IBXwxh9w+LIan6QkA=,tag:hn2aSaDLFmsqxW3SKCsKcQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGtacFd1cDRiaXB0REIw
            Sllyc2F3QUZGNWJJMkJOU3g5a3ZFOUdpU1gwCmh5b2J1YUV2OUIvY0hKamQ4ZVJ0
            TmwzK1VyQjNyOWJoWXpRZkFXRER5U3MKLS0tIGVlM0VLZmxOT1phdjRCTGk4MWxn
            TktTbE1tU1dRYU5KZ1hRa3ZjRG1iMVEK6uNEhG7YjxMRD828MJp2Vfhq7nnX/y+I
            krdqnfpM7Y48HPSKuCB33R4IxbcXer9m5N2+GoyWUjxCgf3MTlAXbg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T00:13:25Z"
    mac: ENC[AES256_GCM,data:jQnC8yDl4xzh+SSRyIC6lDwfkDfcNWgJbaShxRBc0BRNBz5pru+EqkGPIRzQXYjGR6FuB6IFXMuPc025nuXQwsFiYqsSWRey2GlEa8QK6NH88zamSjDocylqCCuDw4iMUXxn50wkr/TelCca67VM842Qlb94M9eT/hU3hzVOuYk=,iv:MZkG9khOOATLHhsqld4cX9gtTfkMkRHAnO/QHqQO/R0=,tag:3hZYRHHd6uFDxw46RHNHFg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
