kind: Secret
ansible_user: ENC[AES256_GCM,data:3QB2xtxwVw==,iv:LzwxSNOluAXRCGl5q2sWL3THKIspdRzSbZvoefTFPds=,tag:jRZUtYkjO6ux84W6qQhaqA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:v3PaCCFL2yAm2O6ephsbVw51DIDVt4SnahPUQLBr41C2BHk0Bg==,iv:WH0EgDjjOCOznyGcyhs0snb3sOjl5kTKf/XXUjMsYTI=,tag:gSkFyuRqdIJ+MsVzVlATlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-11-24T18:45:54Z"
    mac: ENC[AES256_GCM,data:ZvxxAYCikZA/+ot+x2PM4/vbmMVqamINKzYhHnUoUeKJ17YRbnG2opNvPmEKTExt1LRthedGirjhneD5ttP52PVMGNMvqxGeAaus+Ixq+Uktr4YEkvFTl7+WE+r9NxO54BNW87/GCFL//zy3kCvQDPnrnrMhAawIr7UNfaSo/4M=,iv:ZRLx01DchGHUDsZH7riGUyEU82DjVfx1/c9Knjlh7aE=,tag:Wms917tbd5slQXx6ru98UA==,type:str]
    pgp:
        - created_at: "2021-11-24T18:45:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyHd4YJTb9uqAQ/9Ed0uENW2qB10JfO1EdtbF3o74E02vNwCQMzkI4TMBE4P
            10vrcuk1leF5JCL9OVuopovD09s58d5vHqjwIulpjVnOQ/8aUBXySOkLupAKPuAJ
            ORKXT1gnMigP2F4MZ8ggHrnrLOlrWsbCV/ctt77bZeyyN0b8I2ZTZiad20tXTmi9
            R/FxFRg3y5+8ObWAF7W7shJmiwj8/RcE4SaEAQpXhmYmOxD13IvxT/AeDfUQIl+A
            QTBp5/G7XjM9qNTZ6ue/LOjOpT0qepuiFVUKorxTKodi5aRkJ0hn+io2jU0H/FJG
            iAdlz9uJJMpir2cYvoZGeMwKn8R1cngr11GUJUOGIp7YC2KRYvR85EMmycZjqShW
            WTRx8cpRRJjwZol2YzhhwbQw2F+QPFnKHT6W9pOfxdJHhHiaXwQckSjXrOLacIhO
            681e3YLPCe+5aItf3R4vixaKgul3uZPE3Nv3aJClvLqWB5Cu6XB5ipD08tv2aXaB
            kaF0VCtvAChVf6/+P0pMLjuURm41KOBgOpwErIkQEtQwULJHNms1wElpegolE+yW
            PtSLBJNzI9RgYjISf1/bEjfgeL3ueMAS0MhVzDdtvvMEyOuenxKuhQSTuEBJqIsh
            4NtMoZh+z5yNw7EpwroM4Qikmj8raABmlG5lk4yLPQ2JUAqgp1QfW5jS1unkIfvS
            UQER6bLmmYZpHokEODpAbwXwWSapRuJV5e5kpxTGKL3u2atW7Fw2hI6YTwRsSNlZ
            f5nZIemm8BUWoUTxD6zn58Ncy8gUaCyWhr3IZAW9S38hfA==
            =slHo
            -----END PGP MESSAGE-----
          fp: 0F516E8261E8D4D03F62114EBD387FF7BC10AA9D
    unencrypted_regex: ^(kind)$
    version: 3.7.1
