kind: Secret
ansible_user: ENC[AES256_GCM,data:T+v1S/QatA==,iv:eR0TGrl+lmEfxqmQ+fTi8vQaJUn9klO//eY6YNdnd7U=,tag:KyCJ547DDGELvzheuFdSzw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5refq1FgSk1lUI6C/C6W9hYge6w1PF0J/ig4tknqEtlmfh4x6Q==,iv:c9CZNWWKm4K9VR3MO793evih4bSHpji0CniiJKnsvdo=,tag:99cEuMnbGOSZOgjhscocJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcWRHd0dWaGJhKzB2U0F3
            S1pHd1hudUt1aW54WDlESEVoazlIaWRqK0JRCmhwbS8vdXNjSTEvcGxnZXdqaVh0
            YlIvdmp3aVJyM0FHZWhRQ0E2bHptaTQKLS0tIEZvdFRvdTc2UTlOdTZGZGMwV1FX
            dnpwV3F0bTJ0M1RTbzNHYzRmVnlWcUEKg8ANylktz0dAKHbhXVjUKOhjn4x2UUgI
            9t/By/YvMfCycUy4vMakRxF4RnsPR93hFrQvEocJ6h3cD5zWmaXzxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T00:13:25Z"
    mac: ENC[AES256_GCM,data:H81MAYZAmWZNGEsMH8DGnEiy+iQZ6OkF8TUTK8WdQOUj7kXUheGqhuPieTLqO2Y/GjsrFWg0P9Mzs20YzLZVezyOX9GTf+ICC2d93VBVDfbb/jWoXGx7GRczTUC9/vA6R/ak1PY+RQm4fgm38Laiyh0qE/jJM5jk6znwACRjQ0I=,iv:q5MDZMKT/2s3ymLZf1VbSHdxpACCFXsBSBat1YjPxdI=,tag:AuHZQC2ssK1m/ndgm5LScw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
