kind: Secret
ansible_user: ENC[AES256_GCM,data:osTplsS16Q==,iv:Q/9jW5Xd+CYme7pqVxc1ByvHcxP11nzWZt8aOjY+WOw=,tag:dDuRlX+nDWFVBdRuv169Wg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FORHINR5ClqtuBKKRsAToHcIGbaVREgRA4C/JoE=,iv:n2Kr4DGJCwnDL+vz1fohcHkaaDKag17t2P/1EhvfBgc=,tag:ojZg4n96LjkTxgK4B9uq3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVamFheU03cDBWcEF4SHFj
            dUpTNDM3V3FZM2Y1K215UlZ4eFBLQmNhMmhnCjFhK0w2MFpocVcxRHFkMXZGWXRU
            WGRaTlBwdWJMcWU2VC9GMzFmak0xdmcKLS0tIDVSNFJ0YXVNUEZPUEh2YytOak13
            b2V1Q3dUWWs0c0wvbE43Qks4Mk52bTgKv/sV/L2Rd89VoK3YGapcTYlLcU+4bJyF
            eLHY/whYCUWYF9F7+M1+jI1fC4mGiPeClaSl89GHDLegKKcQzJEhOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-07-26T00:13:25Z"
    mac: ENC[AES256_GCM,data:3dUU9UCSwwF8eN1QUiQU52f2rkwEcqdpwBZtFWnESiuxkkoVZYAlY2B6o/VOhnyQJkorp1aHkwLmEUkeWGirXn/9UQV9INokl3uaf5lVqXY5p4nTYdwPm/IKx8X7Zb6TEQQX8pL0qMNV2Q1llo/+Uk+OhhcpSjBLaDnaEjTyzPc=,iv:v0Ou+wOrxUDTdnnrvIK3ehXUzqQ5elzI10t2dA1A6D8=,tag:q0mthOn1iJZJLGvp1aHZaQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
