---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocy-config-v2
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn
