---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: grocy
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: linuxserver/grocy
      tag: 3.3.0

    env:
      TZ: '${TIMEZONE}'

    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_GROCY_ADDR}"
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
        hosts:
          - host: 'grocy.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'grocy.${SECRET_DOMAIN}'
            secretName: 'grocy-tls'

    persistence:
      config:
        enabled: true
        existingClaim: grocy-config-v2
