# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:mekJ0dragnk=,iv:8bi6SgS9Sp6nZXFRuT4rzqwGSXeMQv0k0zjZBZ18wA4=,tag:uEM2LaPFMOrQD8I7KVZIxw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:I5mOpn2GMCj1f+gIP4UuD5VlGbW+o28jag==,iv:Yw9QFJI3JP/cs0kIp5QF2kv1m3C2BcBrLY73LAdzkrI=,tag:YwtdZ/2NBHKVYuHVclfo4g==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:NKmpdFyFCg==,iv:VOpr6CwHyilXMkH0eR8blrpU9H1yarKFUKpQKxlCjgM=,tag:II+wsuloJIJlMSxSTgX1Uw==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:zXXeI5Nb1xNZLrWFEULd7pUkhLhBABIk,iv:wC9J8rXysAAeOqEGzs7jVTW5vGRzhN3b6K25RsWnq+A=,tag:NjjQB1qvE6AeVtG6wXP/Pg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:1xO/ZuHYllJ0smV/68Jt1h5o1H5OGdWdSpzQIhd9ULUftfZKhQ==,iv:MbK4rscquf/iSkXft0zRpfpexbKZA8kseNX5Bh7sn5E=,tag:t5XFpUi5OA03e/Kap1tipg==,type:str]
    SECRET_JUPYTERHUB_CLIENT_ID: ENC[AES256_GCM,data:9e1dKdGD5YmxMy8HLsb9BsrGys4=,iv:NZRzzGQ+PHpO1GkztnnvJfjJrO0G2cziUoJik1VE4Hc=,tag:OOO/2Ulohq+3Im5Vu/Kd6w==,type:str]
    SECRET_JUPYTERHUB_CLIENT_SECRET: ENC[AES256_GCM,data:vg0hFv608Y49vQ9/8nDcFeFUHsi9Wl/lreN2a/A1AkGaoe2SNuYyKw==,iv:qwJ+gzHc9/9ziuSTB7BnilXttIIiYecDRDtYPbXghI0=,tag:Lnn0NuhlbupHoS0T8p5ECg==,type:str]
    SECRET_LONGHORN_BUCKET: ENC[AES256_GCM,data:0sWNvrhKHKT/tvY=,iv:eE6wfvtd0rbmO5BmGiUJJEem45R+0YL7rH49blQ5ENg=,tag:ZA5+pvNMYbR0fnRH1d4RzA==,type:str]
    SECRET_MINIO_ACCESS_KEY: ENC[AES256_GCM,data:sGSf,iv:QsHNtJV2I2A4wOSzEt/qw1DZaym7yrl9qliJrYF2I3c=,tag:PDM6Z8jUBnFFhqZmUa7CWQ==,type:str]
    SECRET_MINIO_SECRET_KEY: ENC[AES256_GCM,data:b4lKHNM2UL4hyEMX+f0k2t13cdPE0Tloq3K0ATapg1L5WHvQRw==,iv:WmlyFZehv7MXgzcXlActBjGvVXDL11A+yIYfqp014pI=,tag:LFjuedTYtVKz+t25UUkD8w==,type:str]
    SECRET_QB_USERNAME: ENC[AES256_GCM,data:Jzfb,iv:zBzjVfN4DM3nYuV5O3nkJfTOAkML3UrCMMTbsXcQkok=,tag:xLRVPPsoU4pUmdTn/t3jvg==,type:str]
    SECRET_QB_PASSWORD: ENC[AES256_GCM,data:swSN/Pc7P7lYcIlz01yVmaY5xv9odwM+,iv:kSwAAFh2K1+EZPcOQ7osjosb80Fp1luLIabPRREfhL0=,tag:U6eKEeaxB8ttLn9ttvhFYA==,type:str]
    SECRET_TRAEFIK_PILOT_TOKEN: ENC[AES256_GCM,data:rtzoxFos/f6eNnmY6SWO6CZynCiD7yohpavwnviwCU6b81TI,iv:4r3L++vjb/xr0p8rKMlSDxVH1HrPhLTDO2GH5rhHVK4=,tag:G4W+Dy3I4goI5s4RKhEi7w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd3BGeGk3ZVRVb1dBSGIw
            T2tLR2hYZmpLZFlLRGdIdlRha2VkNm1hUTAwCm5rZUZvUEF5dVNMVUVPYkpUa1RY
            bmV6ZmRqb20ydWs0ajdaYTY1eGRDUmMKLS0tIGZFUUdpSlNkeGJvb05lcEc0d2Fk
            WTV4NjBwUUtJUkFDUDRIUEhzczhscnMKYkM+Z6zK0B5IpXbaN/qPDjJ/78vG4TZC
            kXuekFZNAbmnrvhgyav0iNcT5yWoQ8pX5ewFc15coAHZK0jJK1+RtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-27T21:05:29Z"
    mac: ENC[AES256_GCM,data:/T8VgMTFuzrZ/+vDYCGJrCHr/vrwGTxMDbjt1M8PknnTUHrxU9x991mWUOSddtGQJgMUpn7ULUKKGUj/pjRqqHrWTUHUCspQK4BN8DAqcXIYvQJGIsq7G6p0/B/I+zmh6yaxCupOYr5fTJxB6eHLAPF82irdwCeYyS5kZlGUVj0=,iv:U5NxsAccqfn1fSNrvlqISWTIT2wLSeLYyAQxswjoiU0=,tag:umtWqQik7G8T2hLR0YX0yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
