apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:UtZoO3D5r4C9+Ot06wg=,iv:de11ubNXJLT+9//Xqs3z6drvFWPp9ceyR26tzm/QdW4=,tag:9q39317jxoV3BSVeztTZ6A==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YK9atocDSFVYIRdxYHViy/mUG/nwsfMIOw==,iv:ut/Lgky7bff6eaALUJB76120g8h5NpJ6WwbwbcCUOlw=,tag:XqPH5z/lZkvyfh5EVE6INw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-07-27T18:23:51Z'
    mac: ENC[AES256_GCM,data:BPLS7zJAtMCIeJB3InQpamWFLqdUCBBXDH+VevbH+Get0tXSUT/nlFe7S+dfWAliaZF7eMn0qu6033aHYLV4SH7umh/m05bNxn4ohIf64cdP/HoeHx5HFvwsdbwrBG6NuSMo5aijEAyU9YqNW5aGSF00tEnXwHa0pH6kVNcXsEY=,iv:V4H/+PuGSzg2O3dHMmNM2jizKpgM3UuzjI/ab8Y/tOE=,tag:EAAB3E23ozi1Isr4KLdTjA==,type:str]
    pgp:
    -   created_at: '2021-07-27T18:23:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9JytBw6RLnDARAAtG9YY8MWAhFm5i4rahA9z9ZaOLKU3/8vADAn7hWGE2GZ
            nUuxiGkIny5jvgEx1iMiqJODJgf7DGcbNhT7+mha1pSZfPhUDGsQnpaqopKvwk7W
            GcNhmGMKcRrBDmEFkWaOkKwPiW5gGS7d5EfVBk/I9hsrPtvgdCo6Mx0B28weSIOU
            STbIwrPf9dKHzx3Br5o1+wf7cPqF9g4DNxAK+uV0zwMNmvB6356QunKYtYyce7+k
            +HUX7JfZxAia765f1J0VJc1uc9i3Nx/QllZVrs7naRUZhcwjMnBH6e27JXTVMPP+
            FaVwh15e6DILI05qU9PGQltj/Tr5cA3y2iX+ZOL50ZJSH9zOvwXaCSr9a/Kzi7o1
            T1ClExw/lsTg1RCHFccINH2DGIJIxc64TIVcvqYwgxWxSbObzH3uTqc/lBfbageO
            dmxQnewfHsFu5KgxBFBQj7MKM4fHw+uD+GIzRO/MElM3pjZUKfTQtp7EV7SAtYaJ
            WZzGtEAgLZZDxD019admDvnZOQiugspjwfZkjczB6irQQS9q5USyb0dZLxJHyGSP
            bD05D8rkImd0bqrN2yEIISzOEyDVWwqB2bwbfWFj6BVQYKJPwE7r9y3yDIHLI+dI
            P2bkBnscHwbB+YnvfYHbY6gBKtXCuEfvP4mlpmnNHbrf4wD6bv3wh/1B3zZUGSTS
            XgHVfbC7Z8cxMtbx1YBwQxHvXB/td9gTk3TI5aXqgumRc5AMMBfMa03bOhUrf5Jj
            BthzAzXcZYq8TgcO3jM4e+uHFTwBWCaUZ/2rRqk6J3R167M9o001z9nCB3pMO64=
            =qZud
            -----END PGP MESSAGE-----
        fp: BE13BE8779CC7A53B2617A7EB59E605BE03ACB5F
    -   created_at: '2021-07-27T18:23:51Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyHd4YJTb9uqARAAiKZfE6KJpn0z1868jDv4hyBUqwj7S2I87hl9u03Bxkud
            A/zVjdjSK/EH5fGcXmmZaTKd0v6FLTDY4mQLZD/tvGLmxullOTdidWKfUrAqVGr8
            9Mq9SRF0EAuaNZDF1qihaBUuO28Dcwu4h+D3CAnfXUwPtWdae5wgeNP5dvlwA1k2
            paQ3anMxUvLatV4trMcYdujweQqEOxck8GCPMXP/xuvQs/5o5xaXLqT3x+uai3WS
            +2IukVY8gi18kzMycEfoo9f59o+tSJC/XkAwHEtUf3PRTCmP85jTLjDLGTU4FeMb
            4um9/5QwehLWobGWWp0Hbuo6g2lH4tzL6u7fCYQ+GBwUNm42quV0n6KtJVoAyYfL
            iXz24ZYEHXtSIiugfyTnYxFUMo42u5OoH0P8lfL0sl2EGsKcnSwgHhzk/m4mWwBp
            Nm2iEtQbvUenpy1jYcYvShGIp0+CL0pKlGHejcoI4M5+NL+KVpFEjmYts8fl3f+q
            s1hKVIFLahFaj/WTg8hb5BK/bqKsRMlL4cnspdA+VZxqKke2VcmQtx8SVrw7Qrvh
            VFeX0c+SEDxCPIojlFiC/95vi40ydblEEZi4nzOIhRLSds1ZT5c0x9ztkfiaCsFx
            7DV39W8kM904JaJ0CGIXDiqQUnsyh9XkAxGnmos9Sl/HUJX9Dr/kDRTqxW0xHq7S
            UQGDfj1UFLl+DpcBN1/i0Bi9YGT17gD4g+wsEsYpj/QqNr1cnJi1+/6hWlKvvNpr
            q/QAbu/0LzxSkvISIQuHIbAqrpg2cTsFRJpqAo7q12MAAg==
            =ErtZ
            -----END PGP MESSAGE-----
        fp: 0F516E8261E8D4D03F62114EBD387FF7BC10AA9D
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
