---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.150-192.168.1.160
  INGRESS_NGINX_LB: 192.168.1.150
  SVC_QBITTORRENT_ADDRESS: 192.168.1.151
  VPN_PORT: "51820"
  VPN_GATEWAY_VPN_PORT: "51820"
  VPN_FORWARDED_PORT_1: "56059"
