---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.rook.io/release
      chart: rook-ceph-cluster
      version: v1.7.0
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  values:
    operatorNamespace: rook-ceph
    toolbox:
      enabled: true
    cephClusterSpec:
      # mon:
      #   allowMultiplePerNode: true
      storage:
        useAllNodes: false
        useAllDevices: false

        nodes:
          - name: 'unas'
            devices: # specific devices to use for storage can be specified for each node
              - name: 'zd0'

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'ceph.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'ceph.${SECRET_DOMAIN}'
