---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deluge
  - qbittorrent
  - jackett
  - lidarr
  - radarr
  - readarr
  - sonarr
  - prowlarr

  - networkPolicy.yaml
