---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bazarr
  - calibre
  - qbittorrent
  - jackett
  - lidarr
  - radarr
  - readarr
  - sonarr
  - prowlarr
  - youtubedl-material
