---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: airsonic
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: airsonic
      version: 6.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: 'America/Chicago'

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'airsonic.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
          - host: "airsonic.192.168.1.150.nip.io"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - 'airsonic.${SECRET_DOMAIN}'
    persistence:
      config:
        enabled: true
        existingClaim: airsonic-config-v1
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs/music
        mountPath: /music
