---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gotenberg
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: gotenberg
      version: 5.0.0
      sourceRef:
        kind: HelmRepository
        name: kurt108-charts
        namespace: flux-system
      interval: 5m
