---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tika
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tika
      version: 2.2.1-full
      sourceRef:
        kind: HelmRepository
        name: tika-charts
        namespace: flux-system
      interval: 5m
