---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-v2
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
