---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.9

    env:
      TZ: 'America/Chicago'

    hostname: qbittorrent

    podAnnotations:
      setGateway: 'true'

    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - "${SVC_QBITTORRENT_ADDRESS}"
        ports:
          bittorrent:
            enabled: true
            port: ${VPN_FORWARDED_PORT_1}
            protocol: TCP
            targetPort: ${VPN_FORWARDED_PORT_1}
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'qb.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'qb.${SECRET_DOMAIN}'

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs
        mountPath: /media

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
