---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.3.5
    env:
      TZ: 'America/Chicago'

    hostname: qbittorrent

    podAnnotations:
      setGateway: 'true'

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'qb.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'qb.${SECRET_DOMAIN}'

    podSecurityContext:
      supplementalGroups:
        - 1
      fsGroupChangePolicy: 'OnRootMismatch'

    persistence:
      config:
        enabled: true
        type: custom
        accessMode: ReadWriteMany
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs/configs

      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs/video
        mountPath: /media

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
