# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: vpn-gateway-vpnconfig
    namespace: vpn
stringData:
    vpnConfigfile: ENC[AES256_GCM,data:92D/ZY7c2JTvpisr0QtC5vKevqj7EXTkz4EgTyLNnqUbYRLBsjEHeQ0TVm+eIiigCZr52vXk4Wf0ZBiteuQLICytiFgONSwUHgUpIxZtU2i0qN3kQoSqVbtlBfL4iLyVDLX1T7Suj+Whx6K/R4eHP/CtmXyvhAQsNv5K8Xeo6GHvVxC89qGZSVrfAo0tVqeohn37skMOzLmiffN34hq/iTbgxk1WbVdhZfnaG+GOyXG8kERW0DD4JdPjBNjQ4mDtd7iA3sjYk6HHfX6bBsFuIKk+B3YAONhIdvAoHgpxUCSddH1gd56a91hWeHqHW5PGXfRpqvVQ2VeoYVi3x6ajLIXQXdfQeL+5ZEN6XA==,iv:Rgy9PK1rUWZxrIp4Vo7Gh3OyiAuM/Z4yW9/ftfoaGE4=,tag:dEYxgiQIzxF4UGXug8saTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVkhDT082WHU0SGJEVkF4
            TThVeFgxcWhEaCtNSkZsZnZORU1IMWpwWjBVCkc2clhzUldZZjJraFRwbnRoVVVK
            V29KRnFUaS9PL3lRT3Z4WlZUREFFaEEKLS0tIEdyM2Q3a2FWZ3Z2Z0gzNHFrNlEw
            U2dUeWJtS1E5Vlg5Tm42YW9QQW5ab1kKnqMqYW86VPHwEoh5b146rnXBMwmWakcU
            K0vj75gKi8gTYi1mK/kDDP9vcqGbWmmp7SuaUwPZhbFqFBhWxuXM2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-05T18:45:00Z"
    mac: ENC[AES256_GCM,data:DpKt0ag5VNVpgqVZXLYXl80nmQs6t39PbT6XuGjet7XO8s61SkqUDcny7KzOZyrCH5JqcMUgC4JAvt2TbZaUnRiBc5tlKDmEDDKla/FCyequmxYgASmYqvhO57Lj/Xa+Mmm2KEVXYHfFQCffJSfDBjAmCxDQRsrjZjS2VrVFGaA=,iv:R42+Ie9UYnrD1Mtk6buaD6oY6hlSq6hbn1hO8JIIwuw=,tag:75071fSN4kFPUS0sEtXBLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
