---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - default
  - dev
  - downloads
  - home
  - flux-system
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - vpn
