apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: teedy-helm-values
  namespace: default
spec:
  backendType: azureKeyVault
  keyVaultName: holthome
  data:
    - key: teedy-helm-values
      name: values.yaml
