---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hedgedoc
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      chart: hedgedoc
      version: 1.1.0
      sourceRef:
        kind: HelmRepository
        name: nicholaswilde-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/hedgedoc
      tag: version-1.9.0
    env:
      TZ: '${TIMEZONE}'
    # envFrom:
    #   - secretRef:
    #       name: home-assistant
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - '${SVC_HOME_ASSISTANT_ADDR}'
        externalTrafficPolicy: Local
    ingress:
      enabled: true
      ingressClassName: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        - host: 'hedgedoc.${SECRET_DOMAIN}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - 'hedgedoc.${SECRET_DOMAIN}'
          secretName: 'hedgedoc-tls'

    persistence:
      config:
        enabled: true
        existingClaim: hedgedoc-config-v1

    mariadb:
      enabled: true
