---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: 'America/Chicago'
      PUID: 568
      PGID: 568

    ingress:
      main:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
        hosts:
          - host: 'calibre-web.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - 'calibre-web.${SECRET_DOMAIN}'
    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v1
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs/books
        mountPath: /books
