---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: v1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 2

    defaultSettings:
      backupTarget: 's3://longhorn@us-east-1/'
      backupTargetCredentialSecret: longhorn-minio-secret

    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      host: 'longhorn.${SECRET_DOMAIN}'
      tls: false
      tlsSecret: longhorn-tls
