# yamllint disable
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: longhorn-b2-secret
    namespace: longhorn-system
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:X6vqoSqXPSbTRG5Fr/XOXuT4BD6GF0nZ3g==,iv:SSpjCm2Ciop2sZsrDz9ANzLRGKJsqNJ0Pzejq7t+Lvw=,tag:AofO8nXdEoKigChPcY514g==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:J8kRWlX1XPOysXNkORRMc2jgV9Hmnhaw5IYUTr802g==,iv:EZttpbe9rIEH7A0voDLG9BeifgnLuV6FyRPL2vEMvNU=,tag:AgtIofogsNDcwS3ps2h0uw==,type:str]
    AWS_ENDPOINTS: ENC[AES256_GCM,data:bAZxD54G4BWEWl6JBpkOfCX3Nosv7GAWgZYdSu6/QoDS2fpIngQ=,iv:+eVZ1ugC1AT9mWv1mJhg9fkZr1yqxzQNTCCseKPUq0w=,tag:OL4+n9bjvlkZY3XNxenYqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQ3FZMzFzc2FSZWsydmZN
            TFpqc014WktqRS93R3lnWktTcXV4YWJVb1JjCnpua3dEejFpL3NFZHp0U2NrZnI4
            c0RNTVVRRjB6S3RmWThMWFVaZmozMXMKLS0tIFB2ZlZXWE8xUWk5UERCMyszTXND
            UUJjSkpwWkFwcUxjSktFb0wrUXFFK1EKNsV3dTCoLMxY576Tl9AHMlwB0fRJ/VEn
            grf/h2Bdmk5ai7j895M8k0YInkTA3wyXNg+5kZjaPhGQWktt2azElg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-09T03:20:35Z"
    mac: ENC[AES256_GCM,data:SKVi6JEwikpIiljUYe5aVUV1WYRX4SBBZKYXFMjTFavAt0QL6d40dp/ezJEVBAdfECns//o0TdfPVZJcDC48vJZ3xy7dwS6ecK8ClV/2T9QAFMP3xzHyqLl8ruGM1wtQM5eftQ73d2AHrd6py3lwqrtxDSZ6JEFBNkKx4yHkkCA=,iv:Z/8y/m1nYMSuCR3+a5NOcdyQQiPp1eAAagPDBfk0L2I=,tag:/Ywbpg47If4ONqJX9V2gsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
