---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 15.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.6.1265
    env:
      TZ: 'America/Chicago'
    ingress:
      main:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
        hosts:
          - host: 'sonarr.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'sonarr.${SECRET_DOMAIN}'
      api:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
        hosts:
          - host: 'sonarr.${SECRET_DOMAIN}'
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - 'sonarr.${SECRET_DOMAIN}'

    podSecurityContext:
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs
        mountPath: /media
    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
