---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hub-db-dir
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
