---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jupyterhub.github.io/helm-chart
      chart: jupyterhub
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: ghcr.io/home-assistant/home-assistant
    #   tag: 2021.8.7
    singleuser:
      image:
        name: jupyter/datascience-notebook
        tag: latest
      defaultUrl: "/lab"
