---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jupyterhub.github.io/helm-chart
      chart: jupyterhub
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jupyterhub-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: ghcr.io/home-assistant/home-assistant
    #   tag: 2021.8.7
    hub:
      config:
        GitHubOAuthenticator:
          client_id: '${SECRET_JUPYTERHUB_CLIENT_ID}'
          client_secret: '${SECRET_JUPYTERHUB_CLIENT_SECRET}'
          oauth_callback_url: 'https://jupyter.${SECRET_DOMAIN}/hub/oauth_callback'
        JupyterHub:
          authenticator_class: github
    singleuser:
      image:
        name: jupyter/datascience-notebook
        tag: latest
      # TODO Add ihaskell
      extraEnv:
        EDITOR: 'vim'
      storage:
        dynamic:
          storageClass: local-path

    ingress:
      enabled: true
      # ingressClassName: 'traefik'
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
        traefik.ingress.kubernetes.io/router.entrypoints: 'websecure'
      hosts:
        - 'jupyter.${SECRET_DOMAIN}'
      tls:
        - hosts:
            - 'jupyter.${SECRET_DOMAIN}'
          secretName: 'jupyter-tls'
