---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v5.21.0

    env:
      TZ: 'America/Chicago'
      PUID: 568
      PGID: 568

    hostname: calibre

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs
        mountPath: /media

    service:
      webserver:
        enabled: true
        # type: ExternalName
        # externalName: calibre.media.svc.cluster.local

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: 'nginx'
        hosts:
          - host: 'calibre.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
          - host: "calibre.192.168.1.150.nip.io"
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - 'calibre.${SECRET_DOMAIN}'

    podSecurityContext:
      supplementalGroups:
        - 100

    resources:
      requests:
        cpu: 0.003
        memory: 768Mi
      limits:
        memory: 1Gi
