apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dev.yaml
  - downloads.yaml
  - home.yaml
  - longhorn-system.yaml
  - media.yaml
  - monitoring.yaml
  - networking.yaml
  - vpn.yaml
